# Generated by Django 4.1.1 on 2022-09-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.PositiveSmallIntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
