# Generated by Django 4.1.1 on 2022-09-21 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviesweb', '0003_movie_description_movie_imdb_rating_movie_poster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField(default=0)),
                ('genre', models.PositiveSmallIntegerField(choices=[(0, 'Action'), (1, 'Comedy'), (2, 'Dramat'), (3, 'Horror'), (4, 'Sci-fi'), (5, 'Other')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='additional_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='moviesweb.additionalinfo'),
        ),
    ]
