# Generated by Django 4.1.1 on 2022-10-03 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesweb', '0006_actor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-year']},
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Akcja'), (1, 'Komedia'), (2, 'Dramat'), (3, 'Horror'), (4, 'Sci-fi'), (5, 'Inny')], default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveSmallIntegerField(default=2000, validators=[django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
